### ISSUE TITLE
Credential Resource needed

### ISSUE THREAD

**Issue by erezo9** [QualiTorque/terraform-provider-torque#74]
Since creating a credential via repo association only creates the credential and doesnt delete it 
there should be a credential resouce
also even put a delete credential variable on removal of the association resouce which will call the credentials api

**Comment by amiros89** [comment]
Added in #75, resource is available starting provider version 0.4.5
Resource documentation is [here](https://registry.terraform.io/providers/QualiTorque/torque/latest/docs/resources/space_git_credentials)
